### ISSUE TITLE
不错啊

### ISSUE THREAD

**Issue by lsj9383** [xiaopihai7256/xiaopihai7256.github.io#1]
哥德巴赫猜想都被验证出来了，果然是震古烁今的奇人。

**Comment by xiaopihai7256** [comment]
acm的题目名字就是这个，好吧夸张了

**Comment by lsj9383** [comment]
毕竟哥德巴赫猜想几百年无解。估计这就是一个哥德尔不完备定理最好的实例之一。

**Comment by lsj9383** [comment]
你数据库用的多么？你知不知道有没有什么工具可以读取在word或excel等office工具中对表的描述，然后再在数据库中创建该表？

**Comment by xiaopihai7256** [comment]
数据库用的不多，只会oracle，倒是没有遇到过类似的需求
